export const contactData = [
  {
    name: "Iqro Centre Sydney",
    address: "39 McCourt Street Wiley Park, NSW 2195 Australia",
    maps: "https://maps.app.goo.gl/ruA3tzJf4iRoyQPL8",
    phone: "+61 422 466 165",
    email: "info@iqro.org.au",
    open_hours: "Everyday, Fajr to Isha",
    href: "/",
    image: "image",
  },
  {
    name: "Iqro Centre Perth",
    address: "39 McCourt Street Wiley Park, NSW 2195 Australia",
    maps: "",
    phone: "+61 422 466 165",
    email: "info@iqro.org.au",
    open_hours: "Everyday, Fajr to Isha",
    href: "/",
    image: "image",
  },
  {
    name: "Melbourne",
    address: "39 McCourt Street Wiley Park, NSW 2195 Australia",
    maps: "",
    phone: "+61 422 466 165",
    email: "info@iqro.org.au",
    open_hours: "Everyday, Fajr to Isha",
    href: "/",
    image: "image",
  },
];
